#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: my_route
#            uri: http://localhost:8081/
#            predicates:
#              - Path=/clients/**
#          - id: my_route2
#            uri: http://localhost:8082/
#            predicates:
#              - Path=/comptes/**

server:
  port: 8888

